apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wpg1nawza-go 
  janus-idp.io/tekton: wpg1nawza-go
  backstage.io/kubernetes-id: wpg1nawza-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wpg1nawza-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml